import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "../components/Nav";
import Footer from "./sections/Footer";
import { CartProvider } from "./context/CartContext";
import NavBottom from "../components/NavBottom";
import Head from "next/head";
import Provider from "../components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MyProject",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Prevent zooming on input focus */}
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        </Head>
      <body className={inter.className}>
      <Provider>
      <CartProvider>
      <Nav />
      <NavBottom />
      {children}
      <Footer />
      </CartProvider>
      </Provider>
      </body>
    </html>
  );
}
